#FROM 724664234782.dkr.ecr.us-east-1.amazonaws.com/library/hardened/seldonio/mlserver:1.6.1-sklearn-2025-09-29
#FROM 724664234782.dkr.ecr.us-east-1.amazonaws.com/library/hardened/seldonio/mlserver:1.6.1-sklearn-2025-07-23
FROM 724664234782.dkr.ecr.us-east-1.amazonaws.com/library/hardened/seldonio/mlserver:1.6.1-sklearn-2025-11-24

USER 0

RUN pip install --upgrade transformers==4.53.0 Brotli==1.2.0 keras==3.12.0 starlette==0.49.1 pip
RUN pip install xgboost

USER 1001
